### ISSUE TITLE
ATLAS ERROR: empty SQL code in Export tab of cohort definitions

### ISSUE THREAD

**Issue by vasanthi014** [Missouri-BMI/OMOP_ON_P_CDM#70]

**Comment by shossain-mizzou** [comment]
I was able to select a cohort and generate reports and sql code
![Image](https://github.com/user-attachments/assets/f414f0d3-872d-4dbd-835a-b44022b00c18)
![Image](https://github.com/user-attachments/assets/b5e60153-8051-481e-8c0b-02d50cf7d860)
