### ISSUE TITLE
ATLAS ERROR: Reviewing Atlas

### ISSUE THREAD

**Issue by mizq7** [Missouri-BMI/OMOP_ON_P_CDM#72]
@shossain-mizzou @vasanthi014 @mosaa While exploring Atlas, I see two issues that probably need attention and modification. 

**Issue 1**
Upon choosing MU CDM and 'Dashboard' as Data Sources in Atlas, it becomes apparent that the X-axis, depicting patients' age on the second graph titled "Age at First Observation," spans from 0 to 2000. Consequently, the graph appears distorted. To rectify this, kindly adjust the X-axis range from 0 to 100. Please find the graph below for reference -
<img width="1599" alt="Screenshot 2024-04-19 at 11 51 31 AM" src="https://github.com/Missouri-BMI/Outback/assets/45376020/d2e9517c-25cf-4e75-8be7-fd9d5eb26e8d">

**Issue 2**
In the third graph on the same Altas interface, "Cumulative Observation" you will see 56 percent of population are identified with negative years. For example, if we cite the graph below as an example, it will mean that 57% of the patient population in this database are observed in the data for negative 3.6 years or more. I am not sure why so many patients are identified with negative years.
<img width="1606" alt="Screenshot 2024-04-19 at 11 58 09 AM" src="https://github.com/Missouri-BMI/Outback/assets/45376020/7430ea6b-63b4-48bb-bfe9-5fb158ac00e5">

**Comment by shossain-mizzou** [comment]
![Image](https://github.com/user-attachments/assets/b4a29cf8-4775-4441-940c-3c44c8b60bf9)
