### ISSUE TITLE
ATLAS ERROR: Incorrect Percentage Calculation in Demographics Characterization

### ISSUE THREAD

**Issue by mizq7** [Missouri-BMI/OMOP_ON_P_CDM#85]
@vasanthi014 @shossain-mizzou 
Atlas' Demographics characterization is consistently calculating incorrect total percentages for subgroups such as SEX, including categories like male, female, No Information, and Unknown. These totals are erroneously exceeding the expected 100%. This issue persists across both complex queries involving over 1800 ICD/CPD codes and simpler queries with a single code. This anomaly indicates a potential systemic error in the percentage calculation or data aggregation process.
<img width="648" alt="image" src="https://github.com/user-attachments/assets/86784536-84a8-4008-9ceb-d536a41c9f79">

<img width="648" alt="image" src="https://github.com/user-attachments/assets/d244d338-1143-4731-9e07-6c2d7f7d2c79">

![Screenshot 2024-08-22 at 10 35 04 AM](https://github.com/user-attachments/assets/01075e0d-4036-4b6c-8a02-20a0b3bf0721)

![Screenshot 2024-08-22 at 10 35 14 AM](https://github.com/user-attachments/assets/6a2a1866-682b-40ed-9c4a-5e5c1344ae9f)

![Screenshot 2024-08-22 at 10 35 22 AM](https://github.com/user-attachments/assets/d8b2f4f2-b59c-43e7-b456-e8b92fd93803)

**Action Item:**
Investigate and resolve the issue of inflated percentages in the Demographics characterization on the Atlas platform. Ensure the total for all subgroups accurately sums to 100%.

I would appreciate your quick suggestions. Please let me know if you have any question on this.

**Comment by shossain-mizzou** [comment]
![Screenshot 2024-10-16 at 4 06 21 PM](https://github.com/user-attachments/assets/2d2f3da3-55ab-4427-849f-19cfc77d7b00)
![Screenshot 2024-10-16 at 4 06 27 PM](https://github.com/user-attachments/assets/7f46c336-eb09-423e-94e4-8e7e33eb5fff)
![Screenshot 2024-10-16 at 4 06 33 PM](https://github.com/user-attachments/assets/29ba4f39-d5ff-4924-b3fd-d67386e86d9d)

Issues are fixed in MU CDM

**Comment by mizq7** [comment]
Thank you @shossain-mizzou
