### ISSUE TITLE
duplicate entries in person table

### ISSUE THREAD

**Issue by shossain-mizzou** [Missouri-BMI/OMOP_ON_P_CDM#91]
select count(*) - count(distinct person_id) from cdm_v3.person;
--69472

**Comment by shossain-mizzou** [comment]
@vasanthi014, @kzraryan-mu duplicate patient entries in pcornet demographic table![Image](https://github.com/user-attachments/assets/ffdf9ce0-b504-4262-bfde-e6d0669325e3)
here is the 14 records for 7 patients.

**Comment by shossain-mizzou** [comment]
as we have duplicates in death table 
```
--death
with duplicate_patients as (
    select patid, count(*) cn from deidentified_pcornet_cdm.cdm.deid_death
    group by patid
    having cn > 1
)
select 
    * 
from deidentified_pcornet_cdm.cdm.deid_death
inner join duplicate_patients
using(patid)
order by patid;
```

**Comment by shossain-mizzou** [comment]
omop cdm suggests: Each Person may have more than one record of death in the source data. It is the task of the ETL to pick the most plausible or most accurate records to be aggregated and stored as a single record in the DEATH table. 

https://www.ohdsi.org/web/wiki/doku.php?id=documentation:cdm:death

**Comment by vasanthi014** [comment]
> @vasanthi014, @kzraryan-mu duplicate patient entries in pcornet demographic table!
> 
> found 12 records for 6 patients.
> 
> ```
> 
> --demographic
> with duplicate_patients as (
>     select patid, count(*) cn from deidentified_pcornet_cdm.cdm.deid_demographic
>     group by patid
>     having cn > 1
> )
> select 
>     * 
> from deidentified_pcornet_cdm.cdm.deid_demographic
> inner join duplicate_patients
> using(patid)
> order by patid;
> ```

This duplication is not in CDM_APPROVED but is in the CDM schema we refresh off cycle(pcornet). @soliman455  applied a fix to delete these duplicate records and we need to implement it in the cleanup.

@shossain-mizzou this should be fixed now

**Comment by vasanthi014** [comment]
> omop cdm suggests: Each Person may have more than one record of death in the source data. It is the task of the ETL to pick the most plausible or most accurate records to be aggregated and stored as a single record in the DEATH table.
> 
> https://www.ohdsi.org/web/wiki/doku.php?id=documentation:cdm:death

We need to update ETL to pick the row with Death_source = D when multiple records exist in death table for same patient.
