### ISSUE TITLE
AWS Service workbench suddenly shutting down or timed out

### ISSUE THREAD

**Issue by mizq7** [Missouri-BMI/OMOP_ON_P_CDM#94]
@vasanthi014 @aaronmbruce @shossain-mizzou:
While working on the project "NextGen_MUIRB2114987" in the AWS service workbench working with RStudio, I see it suddenly shut down. It happened two times. Not sure if it has a time cap. Just wanted to inform if it can be solved. See the image on what happended. I would appreciate any solution.

<img width="573" alt="Screenshot 2024-12-18 at 3 32 03 PM" src="https://github.com/user-attachments/assets/5122ed08-caa4-4733-baef-b40cab180a67" />

**Comment by aaronmbruce** [comment]
Is this on the workspace called idrc-study?

**Comment by mizq7** [comment]
> I have lowered the automatic shutdown threshold on that workspace, which should prevent it from shutting down automatically in the future.

So much appreciated @aaronmbruce
